### ISSUE TITLE
Segfaults with combination of --watch and --tsv or --csv flags

### ISSUE THREAD

**Issue by jindraj** [okbob/pspg#171]
running pspg with `--watch` option without `--csv` or `--tsv` works fine. Pager correctly displays changed content of file.

When pspg is executed **with `--watch` and `--csv` or `--tsv`** the file is displayed once, but when the content is supposed to be refreshed it segfaults.

----
OS: macOS
Architecture: arm64
affected version: several recent versions (3.1.5 to 4.6.3 and 5.0.0), current master included.

**Comment by okbob** [comment]
should be fixed by commit bf04da02bdf04cad8f6360ed8d79467047af1c95 

please check

**Comment by jindraj** [comment]
unfortunately the issue persists. Here's the backtrace from lldb I can try to dig more.
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000018fb46f64 libsystem_platform.dylib`_platform_strlen + 4
libsystem_platform.dylib`_platform_strlen:
->  0x18fb46f64 <+4>:  ldr    q0, [x1]
    0x18fb46f68 <+8>:  adr    x3, #-0xc8                ; ___lldb_unnamed_symbol3$$libsystem_platform.dylib
    0x18fb46f6c <+12>: ldr    q2, [x3], #0x10
    0x18fb46f70 <+16>: and    x2, x0, #0xf
Target 0: (pspg) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000018fb46f64 libsystem_platform.dylib`_platform_strlen + 4
    frame #1: 0x00000001009fa58c pspg`read_and_format [inlined] read_tsv(rb=0x000000016f3f1ea8, linebuf=0x000000016f3f41e8, force8bit=<unavailable>, ifile=0x00000001fac93d30, ignore_short_rows=<unavailable>, opts=0x000000016f3ffce0) at pretty-csv.c:971:22 [opt]
    frame #2: 0x00000001009fa584 pspg`read_and_format(opts=0x000000016f3ffce0, desc=0x000000016f403e90, state=0x000000016f402630) at pretty-csv.c:1476 [opt]
    frame #3: 0x0000000100a06554 pspg`main(argc=<unavailable>, argv=<unavailable>) at pspg.c:3904:12 [opt]
    frame #4: 0x000000018fb1c420 libdyld.dylib`start + 4```

**Comment by okbob** [comment]
Unfortunately this is new bug introduced in 5.0.0. It should be fixed by last commit. Please, check.

**Comment by jindraj** [comment]
It works now 👍, thank you for fixing this so quickly.

**Comment by okbob** [comment]
po 31. 5. 2021 v 9:07 odesílatel Jakub Jindra ***@***.***>
napsal:

> It works now 👍, thank you for fixing this so quickly.
>

Thank you for report
