### ISSUE TITLE
Header detection doesn't work with unicode_header_linestyle=single

### ISSUE THREAD

**Issue by ilmari** [okbob/pspg#18]
Example output:

```
┌────────┬─────────────────────┬───────┬────────┐
│ Schema │        Name         │ Type  │ Owner  │
├────────┼─────────────────────┼───────┼────────┤
│ public │ FROM                │ table │ ilmari │
│ public │ JOIN                │ table │ ilmari │
│ public │ arraytest           │ table │ ilmari │
│ public │ bars                │ table │ ilmari │
└────────┴─────────────────────┴───────┴────────┘
```

**Comment by okbob** [comment]
should be fixed. Thank you for report.

**Comment by ilmari** [comment]
I can confirm that it now works with `unicode_header_linestyle=single`, but a bit more systematic testing reveals that the following combinations still don't work:

border |  column | header
-|-|-
 double | single | single
double | double | single
double | single | double
double | double | double

I've generated a [script](https://github.com/okbob/pspg/files/1296990/border.txt) that can be `\i`-ed in psql to test all the combinations.

**Comment by okbob** [comment]
2017-09-12 20:24 GMT+02:00 Dagfinn Ilmari Mannsåker <
notifications@github.com>:

> I can confirm that it now works with unicode_header_linestyle=single, but
> a bit more systematic testing reveals that the following combinations still
> don't work:
> border column header
> double single single
> double double single
> double single double
> double double double
>
> I've generated a script
> <https://github.com/okbob/pspg/files/1296990/border.txt> that can be \i-ed
> in psql to test all the combinations.
>

I miss support the double border

should be fixed. Please, check.
